5 filtration
Oleg86rus/fast-company pull request #10
Opened 2022-04-13 15:05 UTC by Oleg86rus

2022-04-13 17:10 UTC, AndreiSachuk requested changes

2022-04-13 17:10 UTC, AndreiSachuk commented on src/app/components/pagination.jsx
>          if (itemsCount % pageSize === 0 && currentPage > itemsCount / pageSize) onPageChange(itemsCount / pageSize);
ппц тяжело понять, что тут происходит
по-хорошему ввести переменные, которые назвать понятными словами для человека, что ыб понять, что тут происходит с ходу, а не сидеть и думать что тут такое

2022-04-13 17:10 UTC, AndreiSachuk commented on src/app/components/userLine.jsx
> +        console.log('selectedPROF: ', selectedProf.name);
помним, что перед релизом, когда все отдебажили - чистим

2022-04-13 17:10 UTC, AndreiSachuk commented on src/app/components/userLine.jsx
> +        setSelectedProf(undefined);
когда хотим положить пустоту намеренно - кладем null, так принято

2022-04-14 14:44 UTC, Oleg86rus commented on src/app/components/userLine.jsx
> +        console.log('selectedPROF: ', selectedProf.name);
Удалил лишние консоли

2022-04-14 14:45 UTC, Oleg86rus commented on src/app/components/userLine.jsx
> +        setSelectedProf(undefined);
да, я в уроке услышал про undefined, написал автоматически, а что оставили пустым пропустил.
Исправил.

2022-04-14 17:48 UTC, merged